######################################################################
# Automatically generated by qmake (3.0) ?? 1? 23 09:27:18 2017
######################################################################

TEMPLATE = app
TARGET = QT_5.7
INCLUDEPATH += .

# Input
HEADERS += myclass.h GeneratedFiles/ui_myclass.h
FORMS += myclass.ui
SOURCES += main.cpp myclass.cpp 
RESOURCES += myclass.qrc
QT += widgets
